// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///

//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3rddoHtEyJoD4VkUyNPGIciekuK2yVeQ',
    appId: '1:910032606766:web:da991f7667c2281fbc31bf',
    messagingSenderId: '910032606766',
    projectId: 'flutter-grocery-76cd2',
    authDomain: 'flutter-grocery-76cd2.firebaseapp.com',
    storageBucket: 'flutter-grocery-76cd2.firebasestorage.app',
    measurementId: 'G-L8GRJ2FD27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuz_IaMj5l3ljP7mQkPrq1JumR1i5ueQ',
    appId: '1:910032606766:android:ad65cf8b83a6464bbc31bf',
    messagingSenderId: '910032606766',
    projectId: 'flutter-grocery-76cd2',
    storageBucket: 'flutter-grocery-76cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hcT5xqaqaxcU7vdc7fLSlJlatULMmxY',
    appId: '1:910032606766:ios:c8d0399c23a2e370bc31bf',
    messagingSenderId: '910032606766',
    projectId: 'flutter-grocery-76cd2',
    storageBucket: 'flutter-grocery-76cd2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hcT5xqaqaxcU7vdc7fLSlJlatULMmxY',
    appId: '1:910032606766:ios:c8d0399c23a2e370bc31bf',
    messagingSenderId: '910032606766',
    projectId: 'flutter-grocery-76cd2',
    storageBucket: 'flutter-grocery-76cd2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3rddoHtEyJoD4VkUyNPGIciekuK2yVeQ',
    appId: '1:910032606766:web:815984ecc2560f8cbc31bf',
    messagingSenderId: '910032606766',
    projectId: 'flutter-grocery-76cd2',
    authDomain: 'flutter-grocery-76cd2.firebaseapp.com',
    storageBucket: 'flutter-grocery-76cd2.firebasestorage.app',
    measurementId: 'G-NM8H4B0Q51',
  );
}
